language: python
dist: xenial
sudo: true

python:
  - 3.8

install:
  - pip install -r requirements-dev.txt
  - cp contrib/env-sample .env

script:
  - flake8
  - pytest --cov=receitas

after_success:
  - codecov
