version: "3.3"

services:
  database:
    container_name: receitas_database
    image: postgres:10.10
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=aluradjango
      - POSTGRES_USER=aluradjango
    ports:
      - 5435:5432